"""initial"""

import sqlalchemy as sa
from alembic import op

revision = "60f77c25a94d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit")),
    )
    op.create_table(
        "promo_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("max_activations", sa.Integer(), nullable=False),
        sa.Column("activations_count", sa.Integer(), nullable=False),
        sa.Column("per_user_limit", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "value > 0 AND max_activations > 0 AND per_user_limit > 0 AND activations_count >= 0 AND activations_count <= max_activations",
            name=op.f("ck_promo_codes_limits"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_codes")),
    )
    op.create_index(op.f("ix_promo_codes_code"), "promo_codes", ["code"], unique=True)
    op.create_index(op.f("ix_promo_codes_created_at"), "promo_codes", ["created_at"], unique=False)
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("provider_type", sa.String(length=16), nullable=False),
        sa.Column("external_inbound_id", sa.String(length=64), nullable=True),
        sa.Column("subscription_base_url", sa.Text(), nullable=True),
        sa.Column("max_clients", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "max_clients IS NULL OR max_clients > 0", name=op.f("ck_servers_capacity")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_servers")),
    )
    op.create_index(op.f("ix_servers_created_at"), "servers", ["created_at"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "sponsors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("invite_url", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sponsors")),
        sa.UniqueConstraint("chat_id", name=op.f("uq_sponsors_chat_id")),
    )
    op.create_index(op.f("ix_sponsors_created_at"), "sponsors", ["created_at"], unique=False)
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("daily_price", sa.BigInteger(), nullable=True),
        sa.Column("fixed_price", sa.BigInteger(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(type = 'PAYG' AND daily_price > 0 AND duration_days IS NULL AND fixed_price IS NULL) OR (type = 'SUBSCRIPTION' AND duration_days > 0 AND fixed_price > 0 AND daily_price IS NULL)",
            name=op.f("ck_tariffs_pricing"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariffs")),
    )
    op.create_index(op.f("ix_tariffs_created_at"), "tariffs", ["created_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("balance", sa.BigInteger(), nullable=False),
        sa.Column("referral_balance", sa.BigInteger(), nullable=False),
        sa.Column("referral_earned", sa.BigInteger(), nullable=False),
        sa.Column("referral_code", sa.String(length=32), nullable=False),
        sa.Column("referrer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "balance >= 0 AND referral_balance >= 0", name=op.f("ck_users_nonnegative_balances")
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"], ["users.id"], name=op.f("fk_users_referrer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("referral_code", name=op.f("uq_users_referral_code")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_referrer_id"), "users", ["referrer_id"], unique=False)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_table(
        "ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("wallet", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("wallet IN ('main', 'referral')", name=op.f("ck_ledger_wallet")),
        sa.CheckConstraint("balance_after >= 0", name=op.f("ck_ledger_nonnegative")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_ledger_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger")),
        sa.UniqueConstraint("key", name=op.f("uq_ledger_key")),
    )
    op.create_index(op.f("ix_ledger_user_id"), "ledger", ["user_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=180), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("key", name=op.f("uq_notifications_key")),
    )
    op.create_index(op.f("ix_notifications_sent"), "notifications", ["sent"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_payment_id", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payment_url", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_positive_amount")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_payments_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_payments_idempotency_key")),
        sa.UniqueConstraint("provider", "external_payment_id", name=op.f("uq_payments_provider")),
    )
    op.create_index(op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_payments_external_payment_id"), "payments", ["external_payment_id"], unique=False
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "promo_activations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("promo_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("request_key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["promo_id"], ["promo_codes.id"], name=op.f("fk_promo_activations_promo_id_promo_codes")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_promo_activations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_activations")),
        sa.UniqueConstraint(
            "promo_id", "user_id", "ordinal", name=op.f("uq_promo_activations_promo_id")
        ),
        sa.UniqueConstraint("request_key", name=op.f("uq_promo_activations_request_key")),
    )
    op.create_index(
        op.f("ix_promo_activations_promo_id"), "promo_activations", ["promo_id"], unique=False
    )
    op.create_index(
        op.f("ix_promo_activations_user_id"), "promo_activations", ["user_id"], unique=False
    )
    op.create_table(
        "vpn_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.Column("tariff_id", sa.Integer(), nullable=False),
        sa.Column("external_client_id", sa.String(length=36), nullable=False),
        sa.Column("request_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("protocol", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("desired_enabled", sa.Boolean(), nullable=False),
        sa.Column("provisioned", sa.Boolean(), nullable=False),
        sa.Column("connection_uri", sa.Text(), nullable=True),
        sa.Column("subscription_url", sa.Text(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("price", sa.BigInteger(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("billing_sequence", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"], ["servers.id"], name=op.f("fk_vpn_configs_server_id_servers")
        ),
        sa.ForeignKeyConstraint(
            ["tariff_id"], ["tariffs.id"], name=op.f("fk_vpn_configs_tariff_id_tariffs")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_vpn_configs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vpn_configs")),
        sa.UniqueConstraint("external_client_id", name=op.f("uq_vpn_configs_external_client_id")),
        sa.UniqueConstraint("request_key", name=op.f("uq_vpn_configs_request_key")),
    )
    op.create_index("ix_vpn_billing", "vpn_configs", ["status", "paid_until"], unique=False)
    op.create_index(op.f("ix_vpn_configs_created_at"), "vpn_configs", ["created_at"], unique=False)
    op.create_index(op.f("ix_vpn_configs_server_id"), "vpn_configs", ["server_id"], unique=False)
    op.create_index(op.f("ix_vpn_configs_status"), "vpn_configs", ["status"], unique=False)
    op.create_index(op.f("ix_vpn_configs_user_id"), "vpn_configs", ["user_id"], unique=False)
    op.create_table(
        "withdrawals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("payment_details", sa.Text(), nullable=False),
        sa.Column("request_key", sa.String(length=100), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_withdrawals_positive_amount")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_withdrawals_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_withdrawals")),
        sa.UniqueConstraint("request_key", name=op.f("uq_withdrawals_request_key")),
    )
    op.create_index(op.f("ix_withdrawals_created_at"), "withdrawals", ["created_at"], unique=False)
    op.create_index(op.f("ix_withdrawals_status"), "withdrawals", ["status"], unique=False)
    op.create_index(op.f("ix_withdrawals_user_id"), "withdrawals", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_withdrawals_user_id"), table_name="withdrawals")
    op.drop_index(op.f("ix_withdrawals_status"), table_name="withdrawals")
    op.drop_index(op.f("ix_withdrawals_created_at"), table_name="withdrawals")
    op.drop_table("withdrawals")
    op.drop_index(op.f("ix_vpn_configs_user_id"), table_name="vpn_configs")
    op.drop_index(op.f("ix_vpn_configs_status"), table_name="vpn_configs")
    op.drop_index(op.f("ix_vpn_configs_server_id"), table_name="vpn_configs")
    op.drop_index(op.f("ix_vpn_configs_created_at"), table_name="vpn_configs")
    op.drop_index("ix_vpn_billing", table_name="vpn_configs")
    op.drop_table("vpn_configs")
    op.drop_index(op.f("ix_promo_activations_user_id"), table_name="promo_activations")
    op.drop_index(op.f("ix_promo_activations_promo_id"), table_name="promo_activations")
    op.drop_table("promo_activations")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_external_payment_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_notifications_sent"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_ledger_user_id"), table_name="ledger")
    op.drop_table("ledger")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_referrer_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tariffs_created_at"), table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index(op.f("ix_sponsors_created_at"), table_name="sponsors")
    op.drop_table("sponsors")
    op.drop_table("settings")
    op.drop_index(op.f("ix_servers_created_at"), table_name="servers")
    op.drop_table("servers")
    op.drop_index(op.f("ix_promo_codes_created_at"), table_name="promo_codes")
    op.drop_index(op.f("ix_promo_codes_code"), table_name="promo_codes")
    op.drop_table("promo_codes")
    op.drop_table("audit")
    # ### end Alembic commands ###
